export * from './HeadPage';
export * from './StyledLink';
export * from './Hero';
export * from './PriceCard';
export * from './AccordionPreguntas';
export * from './PreguntasFrecuentes';
export * from './Subscribe';
export * from './ContainerInfo';
export * from './ButtonWhatsApp';
