import { Hero } from '@/components/shared';
import { Box, Typography } from '@mui/material';
import Head from 'next/head';
import RocketIcon from '@mui/icons-material/Rocket';

const cards = [
  {
    title: '¿Quiénes somos?',
    description:
      'Somos la Agencia de Marketing Digital que está revolucionando el modo de hacer crecer pequeñas y medianas empresas mediante servicios de calidad a un precio muy accesible.',
  },
  {
    title: 'Nuestra Misión',
    description:
      'Nuestra misión está en apoyar a las pequeñas y medianas empresas, además a todos aquellos emprendedores que no cuentan con los recursos para contratar personal o agencias de costos elevados para lograr posicionar sus negocios mediante una estrategia de marketing. ',
  },
];

const valores = [
  {
    title: 'Compromiso',
    description:
      'Nos importa generar un ambiente agradable, apto para que cualquier miembro de nuestro equipo pueda desarrollarse plenamente dentro de su área.',
  },
  {
    title: 'Respeto',
    description:
      'Entendemos que cada persona es un mundo, es por eso que damos la libertad para que cada miembro de nuestro equipo se desenvuelva de manera plena e integra.',
  },
  {
    title: 'Comunicación',
    description:
      'La mejor manera para evitar los problemas es contar con una buena comunicación, y nosotros damos la oportunidad de que se expresen con toda libertad.',
  },
];

export default function culturaPage() {
  return (
    <>
      <Head>
        <title>Nuestra Cultura | Social Conecta</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero
          mh='70vh'
          backgroundColor='rgb(115,0,255)'
          backgroundVIDEO='https://vid.cdn-website.com/7b521824/videos/WhTl0SJqSGuK8VrsSRjY_production+ID_4881632+%281%29-v.mp4'
        >
          <Box
            minWidth='80%'
            minHeight='70vh'
            display='flex'
            alignItems='flex-start'
            justifyContent='center'
            flexDirection='column'
            padding='20px 15vw'
            sx={{ color: '#fff' }}
          >
            <Typography
              fontFamily='Poppins'
              fontWeight='bold'
              fontSize='2.5rem'
            >
              Nuestra
            </Typography>
            <Typography fontFamily='Poppins' fontSize='2.5rem'>
              Cultura
            </Typography>
            <Typography fontFamily='Poppins' fontSize='1rem'>
              Conoce Turbo Creativo y el equipo que lo conforma.
            </Typography>
          </Box>
        </Hero>
        <Box
          py='20px'
          minWidth='100vw'
          minHeight='100vh'
          display='flex'
          alignItems='center'
          justifyContent='center'
          flexDirection='column'
          sx={{ backgroundColor: '#fff' }}
          gap='20px'
          position='relative'
        >
          <Typography
            fontFamily='Poppins'
            fontWeight='bold'
            color='rgb(101, 32, 176)'
            fontSize='1.5rem'
            textAlign='center'
          >
            ¡Nosotros somos Turbo Creativo!
          </Typography>
          <div
            className='cuadroBackground'
            style={{
              position: 'absolute',
              top: '10%',
              height: '30%',
              width: '100%',
              backgroundImage:
                'linear-gradient(45deg,rgba(90,19,137,1) 0,rgba(123,0,255,1) 100%)',
              zIndex: 0,
            }}
          ></div>
          <Box
            display='flex'
            width='90%'
            mt='40px'
            alignItems='flex-end'
            justifyContent='center'
            flexDirection={{ xs: 'column', md: 'row' }}
            gap={{ xs: '0px', md: '15px' }}
          >
            <img
              width='100%'
              height='70%'
              alt='Nosotros somos Turbo'
              src='https://lirp.cdn-website.com/5a4f43f8/dms3rep/multi/opt/IMG_0775-1920w.png'
              style={{ zIndex: 0 }}
              className='culturaImg'
            />
            <Box
              display='flex'
              alignItems='center'
              justifyContent='space-between'
              gap='10px'
              flexDirection='column'
              width={{ xs: ' 100%', md: '50%' }}
              zIndex='2'
            >
              {cards.map((c, index) => (
                <Box
                  key={index}
                  display='flex'
                  alignItems='center'
                  justifyContent='center'
                  borderRadius='15px'
                  gap='15px'
                  width='100%'
                  minHeight='40%'
                  padding='20px 30px'
                  boxShadow='rgb(0 0 0 / 10%) 0 3px 11px 0 '
                  sx={{ color: 'rgb(3, 59, 93)', backgroundColor: '#fff' }}
                >
                  <RocketIcon />
                  <Box
                    display='flex'
                    alignItems='flex-start'
                    justifyContent='center'
                    gap='15px'
                    flexDirection='column'
                  >
                    <Typography
                      fontFamily='Poppins'
                      fontWeight='bold'
                      fontSize='1.5rem'
                      variant='h5'
                    >
                      {c.title}
                    </Typography>
                    <Typography
                      fontFamily='Poppins'
                      fontSize='1rem'
                      variant='body1'
                    >
                      {c.description}
                    </Typography>
                  </Box>
                </Box>
              ))}
            </Box>
          </Box>
        </Box>
        <Box
          my='20px'
          minHeight='30vh'
          display='flex'
          width='100vw'
          alignItems='center'
          justifyContent='center'
          flexDirection={{ xs: 'column', md: 'row' }}
          gap='20px'
        >
          {valores.map((v, index) => (
            <Box
              height='100%'
              maxWidth={{ xs: ' 90%', md: '20%' }}
              key={index}
              display='flex'
              gap='15px'
              flexDirection='column'
              alignItems='flex-start'
            >
              <Typography
                fontFamily='Poppins'
                fontWeight='bold'
                color='rgb(3, 59, 93)'
                fontSize='1.5rem'
                variant='h5'
              >
                {v.title}
              </Typography>
              <Typography
                fontFamily='Poppins'
                color='rgb(3, 59, 93)'
                fontSize='0.8rem'
                variant='body1'
              >
                {v.description}
              </Typography>
            </Box>
          ))}
        </Box>
      </main>
    </>
  );
}
